name: Frontend Tests

on:
    push:
        paths:
            - 'frontend/**'
            - '.github/workflows/frontend-*'

env:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/zsceladna_test?serverVersion=17.0&charset=utf8

jobs:
  tests:
    runs-on: ubuntu-latest
    container: ghcr.io/thedevs-cz/php:8.3

    services:
      postgres:
          image: postgres:17.0
          env:
              POSTGRES_PASSWORD: postgres
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          ports:
              - 5432:5432

    steps:
      -   uses: actions/checkout@v4
      -   uses: actions/cache@v4
          with:
              path: ./frontend/vendor
              key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                  ${{ runner.os }}-composer-

      -   run: composer install --no-scripts --no-progress
          working-directory: ./frontend

      -   run: bin/console importmap:install
          working-directory: ./frontend

      -   run: bin/console asset-map:compile
          working-directory: ./frontend

      -   run: vendor/bin/phpunit
          working-directory: ./frontend


  phpstan:
      runs-on: ubuntu-latest
      container: ghcr.io/thedevs-cz/php:8.3
      steps:
        -   uses: actions/checkout@v4
        -   uses: actions/cache@v4
            with:
                path: ./frontend/vendor
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                    ${{ runner.os }}-composer-

        -   run: composer install --no-scripts --no-progress
            working-directory: ./frontend

        -   run: bin/console cache:warmup --env=dev
            working-directory: ./frontend

        -   run: composer run-script phpstan
            working-directory: ./frontend


  migrations-up-to-date:
      runs-on: ubuntu-latest
      container: ghcr.io/thedevs-cz/php:8.3
      services:
          postgres:
              image: postgres:17.0
              env:
                  POSTGRES_PASSWORD: postgres
                  POSTGRES_DB: zsceladna_test
              options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
              ports:
                  - 5432:5432

      steps:
          -   uses: actions/checkout@v4
          -   uses: actions/cache@v4
              with:
                  path: ./frontend/vendor
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

          -   run: composer install --no-scripts --no-progress
              working-directory: ./frontend

          -   run: bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
              working-directory: ./frontend

          -   run: bin/console doctrine:schema:update --dump-sql
              working-directory: ./frontend

          -   run: bin/console doctrine:schema:validate
              working-directory: ./frontend
